services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - modulo3

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports: ["9090:9090"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka:19090,EXTERNAL://0.0.0.0:9090
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:19090,EXTERNAL://localhost:9090
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 300
    depends_on:
      - zookeeper
    networks:
      - modulo3

networks:
  modulo3:
    driver: bridge